classifier_settings:
  test_size: 0.3
  row_data_file: 'data/source.csv'
  prep_data_file: 'data/preprocessed.csv'
  stopwords: ['добрый', 'день', 'пожа', 'любить', 'пожалуйста', 'также', 'a', 'здравствовать', 'ли', 'Здравствуйте',
              'здравствуйте', 'МАИ', 'маи', 'подсказывать', 'уточнять', 'хотеть', 'узнавать', 'таки', 'вечер',
              'именно', 'ребята', 'т', 'е', 'ти', 'Есть', 'быть', 'На']
  exclusionary_stopwords: ['не', 'нет']